apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - name: mydep
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: myserv
spec:
  type: LoadBalancer
  selector:
    app: mydep
  ports:
  - port: 80
    targetPort: 80

        
