apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  storageClassName: efs-sc # Empty string must be explicitly set otherwise default StorageClass will be set
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteMany 