apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpadep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hpadep
  template:
    metadata:
      labels:
        app: hpadep
    spec:
      containers:
      - name: mydep
        image: nginx
        resources: 
          limits: 
            cpu: 200m
          requests:
            cpu: 100m 
---
apiVersion: v1
kind: Service
metadata:
  name: hpaserv
spec:
  type: LoadBalancer
  selector:
    app: hpadep
  ports:
  - port: 80
    targetPort: 80