apiVersion: v1
kind: Pod
metadata:
  name: int-pod 
spec:
  initContainers:
  - name: i1
    image: centos:7
    command: [/bin/sh,-c,"sleep 30"]
  containers:
  - name: n1
    image: tomcat:8
  - name: n2
    image: nginx