apiVersion: v1
kind: Pod
metadata:
  name: livepod
spec:
  containers:
  - name: l1
    image: nginx
    livenessProbe:
      httpGet:
        path: /index1.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5

    
