apiVersion: v1
kind: Namespace
metadata:
  name: newns
---
apiVersion: v1
kind: Pod
metadata:
  name: newpod 
  namespace: newns     
  labels:
    app: newapp 
    env: dev
    client: abc
spec:
  containers:
  - name: n1
    image: tomcat:8
    

