apiVersion: v1
kind: ConfigMap
metadata:
  name: myconf
data:
  username: someuser-updated-2
  uid: someuid-updated-2
---
apiVersion: v1
kind: Pod
metadata:
  name: confpod
  labels:
    name: confpod
spec:
  containers:
  - name: confpod
    image: centos:7
    command: [/bin/sh,-c,"sleep 3600"]
    env:
    - name: e1
      valueFrom:
        configMapKeyRef:
          name: myconf
          key: username
    - name: e2
      valueFrom:
        configMapKeyRef:
          name: myconf
          key: uid
---
apiVersion: v1
kind: Pod
metadata:
  name: confpod-v
  labels:
    name: confpod-v
spec:
  containers:
  - name: confpod
    image: centos:7
    command: [/bin/sh,-c,"sleep 3600"]
    volumeMounts:
    - name: config-vol
      mountPath: /root/data
  volumes:
  - name: config-vol
    configMap:
      name: myconf
    

