apiVersion: v1
kind: ConfigMap
metadata:
  name: myconf
data:
  username: someuser-updated
  uid: someuid-updated
---
apiVersion: v1
kind: Pod
metadata:
  name: confpod
  labels:
    name: confpod
spec:
  containers:
  - name: confpod
    image: centos:7
    command: [/bin/sh,-c,"sleep 3600"]
    env:
    - name: e1
      valueFrom:
        configMapKeyRef:
          name: myconf
          key: username
    - name: e2
      valueFrom:
        configMapKeyRef:
          name: myconf
          key: uid
    

