apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycron
spec:
  schedule: "* * * * *" #per minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: centos:7
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
