apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: UGFzc3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: secpod
  labels:
    name: secpod
spec:
  containers:
  - name: confpod
    image: centos:7
    command: [/bin/sh,-c,"sleep 3600"]
    env:
    - name: e1
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
