apiVersion: v1
kind: ServiceAccount
metadata:
  name: myserviceaccount
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::533266971996:role/EKS-S3ListRole

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  serviceAccountName: myserviceaccount
  containers:
  - name: myapp
    image: amazon/aws-cli
    command: [/bin/sh,-c,'sleep 3600']
    