apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myst
spec:
  selector:
    matchLabels:
      app: myst
  serviceName: stserv
  replicas: 2
  template:
    metadata:
      labels:
        app: myst
    spec:
      containers:
      - name: myst
        image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: stserv
spec:
  type: None
  selector:
    app: myst
  ports:
  - port: 80
    targetPort: 80
