apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mynp
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: ng
  policyTypes:
  - Ingress
  - Egress
  ingress:
  egress: 