apiVersion: v1
kind: Pod
metadata:
  name: readypod
  labels:
    app: ready
spec:
  containers:
  - name: l1
    image: nginx
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /index1.html
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: readyservice
spec:
  type: LoadBalancer
  selector:
    app: ready
  ports:
  - port: 80
    targetPort: 80
