apiVersion: v1
kind: Pod
metadata:
  name: staticpod
spec:
  containers:
  - name: m1
    image: mongo
    volumeMounts:
    - name: myvol
      mountPath: /data/db
  volumes:
  - name: myvol
    awsElasticBlockStore:
      fsType:
      volumeID: vol-010b77ac40c0e45da 
      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  awsElasticBlockStore:
    fsType:
    volumeID: vol-010b77ac40c0e45da
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
